[package]
name = "redis-sentinel-service-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.98.0", features = ["runtime"] }
k8s-openapi = { version = "0.24.0", features = ["latest"] }
redis = { version = "0.27.6" }
